version: '3.8'
services:
  retail-store-app:
    image: registry.digitalocean.com/apo-registry/retail-store-api:latest
    command: sh -c "npx mikro-orm migration:up && node dist/src/main.js"
    ports:
     - '3000:3000'
    environment:
      PRODUCTION: 'true'
      MIKRO_ORM_HOST: 'db'
    depends_on:
     - db