version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  retail-store-app:
    build:
      context: .
      target: ${TARGET}
    command: ${COMMAND}
    ports:
     - '3000:3000'
    volumes: 
      - .:/usr/src/app
    depends_on:
     - db

volumes:
  db:
    driver: local