@startuml entity-relation

entity "Stock" {
*id
--
Quantity
Entry_date
--
Products_id <<FK>>
}

entity "Suppliers" {
*id
--
Name
City
Telephone
Adress
}

entity "Products" {
*id
--
Name
Code
Price
Picture
Nutriscore
Ecoscore
Quantity
Ingredients
--
Brands_id <<FK>>
}

entity "Categories" {
*id
--
Name
--
Aisles_id <<FK>>
}

entity "Products_Categories" {
*id
--
Categories_id <<FK>>
Products_id <<FK>>
}

entity "Aisles" {
*id
--
Name
}

entity "Roles" {
*id
--
Name
}


entity "Roles_aisles" {
*id
--
Aisles_id <<FK>>
Roles_id <<FK>>
}

entity "Users" {
*id
--
FirstName
LastName
Mail
Password
--
Roles_id <<FK>>
}

entity "Orders" {
*id
--
Date
--
Users_id <<FK>>
}

entity "Orders_details" {
*id
--
Quantity
--
Orders_id <<FK>>
Suppliers_id <<FK>>
Products_id <<FK>>
}

entity "Brands" {
*id
--
Name
}


Stock }o..|| Products

Orders_details }o..|| Suppliers
Orders_details }o..|| Products
Orders_details }o..|| Orders

Users }o..|| Roles
Orders }o..|| Users


Aisles ||..o{ Categories
Roles_aisles }o..|| Roles
Roles_aisles }o..|| Aisles


Products ||..o{ Products_Categories
Categories ||..o{ Products_Categories
Products }o..|| Brands


@enduml
